/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import entidades.Categoria;
import javax.swing.JOptionPane;
import persistencia.CategoriaDAO;

/**
 *
 * @author Marcelo
 */
public class TelaCadastroCategoria extends javax.swing.JFrame {

    private Categoria categoria = new Categoria();
    private TelaListaCategoria telaListagem;
    /**
     * Creates new form TelaCadastroCategoria
     */
    public TelaCadastroCategoria(TelaListaCategoria telaListagem) {
        initComponents();
        this.telaListagem = telaListagem;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
        txtCategoria.setText(categoria.getNome());
        if (categoria.getTipo() == 'F') {
            rdbFilme.setSelected(true);
        } else if (categoria.getTipo() == 'J') {
            rdbJogo.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rdbFilme = new javax.swing.JRadioButton();
        rdbJogo = new javax.swing.JRadioButton();
        txtCategoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Categoria");

        grpTipo.add(rdbFilme);
        rdbFilme.setText("Filme");

        grpTipo.add(rdbJogo);
        rdbJogo.setText("Jogo");

        jLabel2.setText("Tipo");

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGravar)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbJogo))
                    .addComponent(jLabel1)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbJogo)
                    .addComponent(rdbFilme))
                .addGap(18, 18, 18)
                .addComponent(btnGravar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        categoria.setNome(txtCategoria.getText());
        if (rdbFilme.isSelected()) {
            categoria.setTipo('F');
        } else if (rdbJogo.isSelected()) {
            categoria.setTipo('J');
        } 
        
        if (categoria.getTipo() != ' ') {
            
            if (categoria.getId() == 0) {
                inserir();
            } else {
                alterar();
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Selecione o tipo de categoria");
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void inserir() {
        if (CategoriaDAO.inserir(categoria)) {
            JOptionPane.showMessageDialog(this, "Categoria inserida com sucesso!");
            telaListagem.montarListaCategorias();
            dispose(); // fechar a tela de cadastro
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao inserir categoria");
        }
    }
    
    private void alterar() {
        if (CategoriaDAO.alterar(categoria)) {
            JOptionPane.showMessageDialog(this, "Categoria alterada com sucesso!");
            telaListagem.montarListaCategorias();
            dispose(); // fechar a tela de cadastro
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar categoria");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.ButtonGroup grpTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rdbFilme;
    private javax.swing.JRadioButton rdbJogo;
    private javax.swing.JTextField txtCategoria;
    // End of variables declaration//GEN-END:variables
}
